services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    ports:
      - "3000:8080"
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
      #GLOBAL_LOG_LEVEL: DEBUG
    volumes:
      - ./open-webui:/app/backend/data

  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    environment:
      NVIDIA_VISIBLE_DEVICES: all
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              driver: nvidia
              count: all
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama # Model (LLM) storage
